server:
  port: ${MSW_SERVER_PORT:8080}
  ssl:
    enabled: ${MSW_SSL_ENABLED:false}
    key-store-type: ${MSW_SSL_KEYSTORE_TYPE}
    key-store: ${MSW_SSL_KEYSTORE_PATH}
    key-store-password: ${MSW_SSL_KEYSTORE_PASSWORD}
    key-alias: ${MSW_SSL_KEY_ALIAS}
    trust-store-type: ${MSW_SSL_TRUSTSTORE_TYPE:}
    trust-store: ${MSW_SSL_TRUSTSTORE_PATH:}
    trust-store-password: ${MSW_SSL_TRUSTSTORE_PASSWORD:}
app:
  twitch-client-id: ${TWITCH_CLIENT_ID:}
